### ISSUE TITLE
Create spindle or progress bar when processing file.

### ISSUE THREAD

**Issue by vigliensoni** [lingxiaoyang/Tension-Analysis#1]
This can be tricky, but users should be able to know their file is being processed.

If it is hard to retrieve a signal from the app to estimate remaining processing time, we should display a spindle icon or a piece of text saying "analyzing", "processing", or "tricking you".

**Comment by lingxiaoyang** [comment]
A new version is now updated with this feature: e794cff93be9a9b2846d4a5739ae4e888280bc1a

**Comment by vigliensoni** [comment]
And it's working nicely! How often is the percentage process refresh?

@cordltx any ideas for styling the processing information?

**Comment by lingxiaoyang** [comment]
@vigliensoni It's every 5 sec, but totally adjustable in the frontend.

**Comment by lingxiaoyang** [comment]
@vigliensoni For better styling, the request can be made AJAX also!
