### ISSUE TITLE
Add License.

### ISSUE THREAD

**Issue by vigliensoni** [lingxiaoyang/Tension-Analysis#5]
We should ask @jumayel06 about the license they want to have.

**Comment by jumayel06** [comment]
Hi, we would like to have the following license. Thanks

**Attribution-ShareAlike 
CC BY-SA**

_This license lets others remix, tweak, and build upon your work even for commercial purposes, as long as they credit you and license their new creations under the identical terms. This license is often compared to “copyleft” free and open source software licenses. All new works based on yours will carry the same license, so any derivatives will also allow commercial use. This is the license used by Wikipedia, and is recommended for materials that would benefit from incorporating content from Wikipedia and similarly licensed projects._

More details: 
https://creativecommons.org/licenses/by-sa/4.0
https://creativecommons.org/licenses/by-sa/4.0/legalcode

**Comment by vigliensoni** [comment]
Hi @jumayel06 ,

I read this from the [Creative Commons FAQ:](http://wiki.creativecommons.org/Frequently_Asked_Questions#Can_I_apply_a_Creative_Commons_license_to_software.3F)

Can I apply a Creative Commons license to software?

We do not recommend it. Creative Commons licenses should not be used for software. We strongly encourage you to use one of the very good software licenses which are already available. We recommend considering licenses made available by the Free Software Foundation or listed at the Open Source Initiative. Unlike our licenses, which do not make mention of source or object code, these existing licenses were designed specifically for use with software. Furthermore, our licenses are not compatible with the GPL, the most frequently used free software license.

Note that the CC0 Public Domain Dedication is GPL-compatible and acceptable for software. For details, see the relevant CC0 FAQ entry.

The recommended licenses that Github recommends are:

<img width="277" alt="Screen Shot 2019-07-10 at 3 36 38 PM" src="https://user-images.githubusercontent.com/492229/60973439-96785a80-a328-11e9-9042-9dd9580101d0.png">

But it's your call, let us know :)

**Comment by jumayel06** [comment]
Hi @vigliensoni I had a talk with Dr. High, we will go with one of the recommended licenses you mentioned. You can choose the most appropriate one from the list. Thanks

**Comment by vigliensoni** [comment]
Thank you @jumayel06 

We will go, then, with MIT. It is simple and permissive. See https://choosealicense.com/licenses/mit/
